collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

#source: ./src

#destination: ./dist

sass:
  sass_dir: assets/_sass
  style: compressed

exclude: [
  src,
  node_modules,
  package.json,
  package-lock.json,
  rollup.config.js,
  webpack.config.js,
  Gemfile,
  Gemfile.lock,
  assets/_sass,
  assets/_js,
  example
]

title: '@pix8/ TMG technical assessment'
#logo: /assets/img/logo.png
logo: /assets/img/pixie-dust.gif
description: A Flickr public feed component built in react
show_downloads: true
google_analytics:

repository: pix8/tmg-technical-test
#theme: jekyll-theme-minimal